---
# tasks file for go

- name: "Downloading and extracting {{ go_app }} {{ go_version }} on EL based systems."
  unarchive:
    src: "{{ go_dl_url }}"
    dest: "{{ go_bin_path }}"
    remote_src: yes

- name: "Placing {{ go_profile_template_dest_file }} in {{ go_profile_template_path }} for system-wide availability on EL based systems"
  template:
    src: "{{ go_profile_template_source_file }}"
    dest: "{{ go_profile_template_path }}/{{ go_profile_template_dest_file }}"
  notify:
    - "Source {{ go_profile_template_path }}/{{ go_profile_template_dest_file }} to take effect system-wide and be available with new login shell"
