---
# handlers file for go

- name: "Source {{ go_profile_template_path }}/{{ go_profile_template_dest_file }} to take effect system-wide and be available with new login shell"
  shell: ". {{ go_profile_template_path }}/{{ go_profile_template_dest_file }}"
  args:
    executable: /bin/bash
